# -*- coding: utf-8 -*-
"""Array_Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlO3Tgl725qXuqQJ-zMd-5kOsB4CmyDh

Static Declaration of Arrays
"""

import array as ar 
Col=ar.array('I',[10,20,-19,87,33])
for value in Col:  
  print(value)

from array import *
b=array('i',[10,-20,30])
for i in b:
  print(i)

from array import *
col=array('i',[10,22,66,57,73,82])
for iter in range(0,len(col)):
  print(col[iter])

"""Dynamic Declaration of Array"""

arr=[int(x) for x in input("Enter element").split(',')]
for i in range(0,len(arr)):
  print(arr[i])

"""Appending elements in an array"""

from array import *
a=array('i',[])
a.append(10)
a.append(20)
a.append(38)
a.append(49)
a.append(50)
for i in range(len(a)):
  print(a[i])
# Inserting elements in an array
a.insert(2,100)
# Printing the elements 
for i in range(len(a)):
  print(a[i])
# Deleting elements from an array 
a.pop(3)
for i in range(len(a)):
  print(a[i])

# Find the minimum element the array
arr=[int(x) for x in input("Enter the elements in an array").split(',')]
min=arr[0]
ind=0
for iter in range(1,len(arr)):
  if arr[iter]<min:
    min=arr[iter]
    ind=iter
print("The minimum element of an array is {} at position {}".format(min,ind))

# Store the even and odd elements of an array in different arrays 
from array import *
arr=[int(x) for x in input("Enter a number").split(',')]
arr_odd=array('i',[])
arr_even=array('i',[])
for iter in arr:
  if iter%2==0:
    arr_even.append(iter)
  else:
    arr_odd.append(iter)
for i in arr_even:
  print(i,end=" ")
print('\n')
for j in arr_odd:
  print(j,end=" ")

from array import * 
str=input("Enter marks").split(" ")
marks=[int(x) for x in str]
sum=0
for value in marks:
  print(value)
  sum+=value
print("Total Marks", sum)
# Percentage 
n=len(marks)
percent=sum/n
print("percentage",percent)

# Enter elements in an array and convert -ve into 0
from array import *
arr=array('i',[])
length=int(input("enter length of the array"))
for iter in range(0,length):
  arr.append(int(input()))
print('\n')
for iter in range(0,length):
  if arr[iter]<0:
    arr[iter]=0
for value in arr:
  print(value,end=" ")

# delete positive elements in an array 
from array import * 
arr=array('i',[])
n=int(input("enter the length"))
for iter in range(0,n):
  arr.append(int(input()))
print('\n')
iter=0
# iter is for positioning 
for val in arr:
    if val > 0:
        arr.pop(iter)
    iter+=1
for value in arr:
  print(value,end=" ")

# Linear Search
from array import * 
arr=array('i',[])
n=int(input("Enter the length of an array"))
for iter in range(0,n):
  arr.append(int(input()))
item=int(input("Emter the item to be searched"))
for iter in range(0,n):
  if arr[iter]==item:
    print("Element {} found at {}".format(arr[iter],iter))
    break
else:
  iter+=18
print(iter)
if iter==n:
  print("Element not found ")

# Frequency of element in an array
from array import * 
arr,count=array('i',[]),0
n=int(input("Enter the length of an array"))
for iter in range(0,n):
  arr.append(int(input()))
item=int(input("Emter the item to be searched"))
for value in arr:
  if value==item:
    count+=1
if count==0:
  print("Value not found")
else:
  print("The value {} occured {} times".format(item,count))

# Move all the negative numbers to one side of an array
from array import * 
arr,arr_pos,arr_neg=array('i',[10,-2,0,-1,-25,22,87,97]),array('i',[]),array('i',[])
for iter in range(0,len(arr)):
  if arr[iter]<0:
    arr_neg.append(arr[iter])
  else:
    arr_pos.append(arr[iter])
print()
arr_neg.extend(arr_pos)
for value in arr_neg:
  print(value,end=" ")

"""Doubts
1. How to delete an element from an array, without using array index out of bound
2. Intersection and union of two arrays in python
3. 
"""



# Find the union and intersection of two arrays 
from array import * 
arr1,arr2,arr_union,arr_intersect=[1,2,3,4,5],[1,6,7,8],[],[]
hey=arr1
arr1.extend(arr2)
for value in arr1:
  print(value,end=" ")
for value in arr2:
  if value in hey:
      arr_intersect.append(value)
for value in arr_intersect:
  print(value)

#v Find the subarray of the non negative numbers 
from array import *
arr=array('i',[1,4,20,3,10,5])
start,stop,sum=int(input()),int(input()),0
for iter in range(start,stop+1):
  sum+=arr[iter]
print("Sum of elements=",sum)

# Rotate the elements of an array by 1 
from array import *
arr=array('i',[1,4,20,3,10,5])
last=arr[-1]
arr.pop(-1)
arr.reverse()
arr.append(last)
arr.reverse()
for value in arr:
  print(value)