# -*- coding: utf-8 -*-
"""Array_Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlO3Tgl725qXuqQJ-zMd-5kOsB4CmyDh

Static Declaration of Arrays
"""

import array as ar 
Col=ar.array('I',[10,20,-19,87,33])
for value in Col:  
  print(value)

from array import *
b=array('i',[10,-20,30])
for i in b:
  print(i)

from array import *
col=array('i',[10,22,66,57,73,82])
for iter in range(0,len(col)):
  print(col[iter])

"""Dynamic Declaration of Array"""

arr=[int(x) for x in input("Enter element").split(',')]
for i in range(0,len(arr)):
  print(arr[i])

"""Appending elements in an array"""

from array import *
a=array('i',[])
a.append(10)
a.append(20)
a.append(38)
a.append(49)
a.append(50)
for i in range(len(a)):
  print(a[i])
# Inserting elements in an array
a.insert(2,100)
# Printing the elements 
for i in range(len(a)):
  print(a[i])
# Deleting elements from an array 
a.pop(3)
for i in range(len(a)):
  print(a[i])

